plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.aflow.app'
    compileSdk 34

    defaultConfig {
        applicationId "dev.aflow.app"
        minSdk 26
        targetSdk 34
        versionCode project.hasProperty('versionCode') ? project.property('versionCode').toInteger() : 1
        versionName project.hasProperty('versionName') ? project.property('versionName') : "1.0-dev"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }
}
